services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"yourStrong(!)Password\" -Q \"SELECT 1\" -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

  nopcommerce:
    image: nopcommerceteam/nopcommerce:latest
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - nop_appdata:/app/App_Data

volumes:
  sql_data:
  nop_appdata:
